/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("io.netty:netty-all:4.1.76.Final");
    compileOnly("org.projectlombok:lombok:1.18.24");
    annotationProcessor("org.projectlombok:lombok:1.18.24");

    // Tests
    testImplementation("junit:junit:4.13.2");
    testCompileOnly("org.projectlombok:lombok:1.18.24");
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24");
}
